"""Add title to Note and complete to Todo

Revision ID: d12b2cedee3e
Revises: 
Create Date: 2024-06-24 00:01:52.003499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12b2cedee3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=True))

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('completed')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
